config/routes.rb
RedditClone::Application.routes.draw do
  root to: "sessions#new"
  resources :users
  resource :session
  resources :subs
  resources :links do
    post 'upvote', to: "user_votes#create"
    post 'downvote', to: "user_votes#create"
  end
  resources :comments
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  body              :text
#  user_id           :integer
#  parent_comment_id :integer
#  link_id           :integer
#  created_at        :datetime
#  updated_at        :datetime
#

class Comment < ActiveRecord::Base
  validates :body, :presence => true

  has_many :comments, :inverse_of => :parent_comment,
    :foreign_key => :parent_comment_id

  belongs_to :parent_comment, :inverse_of => :comments,
    :class_name => "Comment"

  belongs_to :link
  belongs_to :user

  def comments_by_parent_id
    top_level_comments = self.comments
    comment_chains = {}
    top_level_comments.map do |comment|
      comment_chains[comment.id] = comment.comments
    end
    comment_chains
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    render :new
  end

  def create
    @link = Link.find(params[:comment][:link_id])
    @comment = @link.comments.new(comment_params)
    flash[:errors] = @comment.errors.full_messages unless @comment.save
    redirect_to link_url(@link)
  end

  def show
    @existing_comment = Comment.find(params[:id])
    @comment = Comment.new
    render :show
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy!
    redirect_to link_url(@comment.link)
  end

  private
  def comment_params
    comment_params = params.require(:comment)
                           .permit(:body, :link_id, :parent_comment_id)
    comment_params[:user_id] = current_user.id
    comment_params
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= comment.body %>

<% comment.comments.each do |c|%>
<ul><%= render "comments/comment", :comment => c %></ul>
<% end %>

app/views/comments/_form.html.erb
<% action = (@comment.persisted? ? comment_url(@comment) : comments_url )%>
<% title = (@comment.persisted? ? "Edit Comment" : "Submit Comment")%>

<h1><%= title %></h1>

<form action="<%= action %>" method="POST">
  <%= csrf_token %>
  <%= patch_method %>

  <% if @link %>
    <input type="hidden" name="comment[link_id]" value="<%= @link.id %>">
  <% end %>

  <% if params[:controller] == "comments" && params[:action] == "show" %>
    <input type="hidden" name="comment[parent_comment_id]" value="<%= params[:id] %>">
    <input type="hidden" name="comment[link_id]" value="<%= @existing_comment.link.id %>">
  <% end %>


  <p>
    <label>Comment
      <input type="text" name="comment[body]" value="<%= @comment.body %>">
    </label>

  <input type="submit" value="<%= title %>">
  </p>
</form>

app/views/comments/show.html.erb
<%= @existing_comment.link.title %>
<%= @existing_comment.body %>
<%= render "form" %>