config/routes.rb
RedditClone::Application.routes.draw do
  root to: "sessions#new"
  resources :users
  resource :session
  resources :subs
  resources :links do
    post 'upvote', to: "user_votes#create"
    post 'downvote', to: "user_votes#create"
  end
  resources :comments
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  url        :string(255)      not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Link < ActiveRecord::Base
  validates :title, :url, :user, :presence => true

  belongs_to :user, :inverse_of => :links
  has_many :sub_links, :inverse_of => :link
  has_many :subs, :through => :sub_links
  has_many :comments, :inverse_of => :link
  has_many :votes, :class_name => "UserVote"

  def comments_by_parent_id
    top_level_comments = self.comments
    comment_chains = {}
    top_level_comments.map do |comment|
      comment_chains[comment.id] = comment.comments
    end
    comment_chains
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :verify_logged_in
  before_action :get_all_subs, except: [:destroy]
  before_action :find_link, only: [:edit, :update, :destroy]

  def index
    redirect_to sub_url(params[:sub_id])
  end

  def show
    @link = Link.find(params[:id])
    @comment = Comment.new
    render :show
  end

  def new
    @link = Link.new
    @link_subs = []
    render :new
  end

  def create
    @link = current_user.links.new(link_params)
    @link_subs = @link.subs.includes(:moderator)

    if @link.save
      flash[:notice] = "Thanks for your submission!"
      redirect_to sub_url(params[:sub_id])
    else
      flash[:errors] = @link.errors.full_messages
      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    if @link.update_attributes(link_params)
      flash[:notice] = "Link updated!"
      redirect_to sub_url(params[:sub_id])
    else
      flash[:errors] = @link.errors.full_messages
      render :edit
    end
  end

  def destroy
    @link.destroy!
    redirect_to sub_url(params[:sub_id])
  end

  private
  def get_all_subs
    @all_subs = Sub.all
  end

  def link_params
    params.require(:link).permit(:title, :url, :sub_ids => [])
  end

  def find_link
    @link = current_user.links.includes(:subs).find(params[:id])
    @link_subs = @link.subs
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<% action = (@link.persisted? ? link_url(@link) : links_url )%>
<% title = (@link.persisted? ? "Edit Link" : "Submit Link")%>

<h1><%= title %></h1>

<form action="<%= action %>" method="POST">
  <%= csrf_token %>

  <p>
    <label>Link Title
      <input type="text" name="link[title]" value="<%= @link.title %>">
    </label>

    <label>Link URL
      <input type="text" name="link[url]" value="<%= @link.url %>">
    </label>
    <br>

    <% @all_subs.each do |sub| %>
      <label><%= sub.name %>
      <input type="checkbox" name="link[sub_ids][]" value="<%= sub.id %>"       <%= "checked".html_safe if @link_subs.include?(sub)%>>
      </label>
    <% end %>

  <input type="submit" value="<%= title %>">
  </p>
</form>

app/views/links/edit.html.erb
<%= render "form" %>

app/views/links/new.html.erb
<%= render "form" %>

app/views/links/show.html.erb
<% karma = 0 %>
<% @link.votes.each do |vote| %>
  <% vote.up ? karma += 1 : karma -= 1 %>
<% end %>

<h1><%= @link.title %></h1>

<%= render "comments/form" %>

Karma: <%= karma %>

<form action="<%=link_upvote_url(@link)%>" method="POST">
  <%= csrf_token %>
  <input type="hidden" name="vote[up]" value="true">
  <input type="hidden" name="vote[link_id]" value="<%= @link.id %>">
  <input type="submit" value="UPBOAT">
</form>

<form action="<%=link_downvote_url(@link)%>" method="POST">
  <%= csrf_token %>
  <input type="hidden" name="vote[up]" value="false">
  <input type="hidden" name="vote[link_id]" value="<%= @link.id %>">
  <input type="submit" value="DOWNBOAT">
</form>

<% @link.comments.each do |comment| %>
  <% unless comment.parent_comment_id %>
    <p><%= render "comments/comment", :comment => comment %></p>
  <% end %>
<% end %>