config/routes.rb
RedditClone::Application.routes.draw do
  root to: "sessions#new"
  resources :users
  resource :session
  resources :subs
  resources :links do
    post 'upvote', to: "user_votes#create"
    post 'downvote', to: "user_votes#create"
  end
  resources :comments
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  mod_id     :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Sub < ActiveRecord::Base
  validates :name, :mod_id, :presence => true

  belongs_to :moderator, :inverse_of => :moderated_subs,
  :foreign_key => :mod_id,
  :class_name => "User"

  has_many :sub_links, :inverse_of => :sub
  has_many :links, :through => :sub_links
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :verify_logged_in, except: [:index, :show]
  before_action :find_sub, only: [:show, :edit, :update, :destroy]
  before_action :verify_moderator, only: [:edit, :update, :destroy]

  def index
    @subs = Sub.all
    render :index
  end

  def show
    render :show
  end

  def new
    @sub = Sub.new
    5.times { @sub.links.new }
    @links = @sub.links
    render :new
  end

  def create
    @sub = current_user.moderated_subs.new(sub_params)
    @sub.links.new(links_params)

    @links = @sub.includes(:links)
    if @sub.save
      flash[:notice] = "#{ @sub.name } created successfully!"
      redirect_to sub_url(@sub)
    else
      (5 - links_params.count).times { @sub.links.new }
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    if @sub.update_attributes(sub_params)
      flash[:notice] = "#{ @sub.name } updated successfully!"
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def destroy
    @sub.destroy!
    redirect_to subs_url
  end

  private
  def sub_params
    params.require(:sub).permit(:name)
  end

  def links_params
    params.permit(:links => [:title, :url]).require(:links).values
          .reject{ |data| data.values.all?(&:blank?) }
          .map { |data| data[:user_id] = current_user.id; data }
  end

  def find_sub
    @sub = Sub.find(params[:id])
  end

  def verify_moderator
    redirect_to subs_url unless @sub.mod_id == current_user.id
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<% action = (@sub.persisted? ? sub_url(@sub) : subs_url )%>
<% title = (@sub.persisted? ? "Edit Sub" : "Create Sub")%>

<h1><%= title %></h1>

<form action="<%= action %>" method="POST">
  <%= csrf_token %>
  <% if @sub.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label>Sub Name
    <input type="text" name="sub[name]" value="<%= @sub.name %>">
  </label>

  <% unless @sub.persisted? %>
    <% @links.each_with_index do |link, i| %>
  <p>
    <label>Link <%= i + 1 %> Title
      <input type="text" name="links[<%= i %>][title]" value="<%= @links[i].title %>">
    </label>

    <label>Link <%= i + 1 %> URL
      <input type="text" name="links[<%= i %>][url]" value="<%= @links[i].url %>">
    </label>
  </p>
    <% end %>
  <% end %>

  <input type="submit" value="<%= title %>">
</form>

app/views/subs/new.html.erb
<%= render "form" %>

app/views/subs/show.html.erb
<h1><%= @sub.name %></h1>

<% @sub.links.each do |link| %>
  <%= link_to link.title, link.url %>
  <%= button_to "Delete", link_url(link), method: :delete %>
  <br>
<% end %>

<%= link_to "Submit a Link", new_link_url %>